### ISSUE TITLE
CMD, CLK, SD0, SD1 have been used by internal spi flash

### ISSUE THREAD

**Issue by xiongyumail** [ATmega8/ESP32-Audio#1]
Hi @ATmega8 
There are some issues about `CMD, CLK, SD0, SD1`
![image](https://user-images.githubusercontent.com/13846382/45838203-ad4db200-bd00-11e8-8048-174b4f685046.png)

Some good examples：

<https://github.com/OLIMEX/ESP32-EVB/blob/master/HARDWARE/REV-D/ESP32-EVB_Rev_D.pdf>
<https://github.com/whyengineer/esp32_circle/blob/master/hardware/V0B/esp32_v0b.pdf>
<https://github.com/m5stack/M5-3D_and_PCB/blob/master/M5_Core_SCH(20171206).pdf>
<https://dl.espressif.com/dl/schematics/esp32-lyrat-v4-schematic.pdf>

**Comment by ATmega8** [comment]
thanks you PR, i fixed it with new commit.
